apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.kong_api_uri | replace "." "-" }}
spec:
  secretName: {{ print .Values.kong_api_uri "-tls" | replace "." "-" }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.kong_api_uri }}
  dnsNames:
  -  {{ .Values.kong_api_uri }}      