apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ print .Values.app_name "-identity" }}
spec:
  type: 0
  resourceID: {{ .Values.msi_resource_id }}
  clientID: {{ .Values.msi_client_id }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ print .Values.app_name "-identity-binding" }}
spec:
  azureIdentity: {{ print .Values.app_name "-identity" }}
  selector: {{ .Values.msi_selector }}