apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Values.app_name "-onsleep" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print .Values.app_name "-onsleep" }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: {{ print .Values.app_name "-config" | quote }}
        dapr.io/app-id: {{ print .Values.app_name "-onsleep" | quote  }}
        dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        {{ print .Values.app_name "/config-hash" }}: {{ include (print $.Template.BasePath "/components.yaml") . | sha256sum }}
      labels:
        app: {{ print .Values.app_name "-onsleep" }}
        aadpodidbinding: {{ .Values.msi_selector }}
    spec:
      containers:
      - name: eventhandler
        image: {{  print .Values.acr_name ".azurecr.io/traduire/onsleep.handler:" .Values.commit_version | nospace  }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: TRADUIRE_SLEEP_TIME
          value: {{ print .Values.delay_time_in_seconds | quote  }}
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "traduire"
        effect: "NoSchedule"