apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: "keda-pod-identity"
spec:
  type: 0
  resourceID: {{ .Values.keda_msi_resource_id }}
  clientID: {{ .Values.keda_msi_client_id }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: "keda-pod-identity-binding"
spec:
  azureIdentity: "keda-pod-identity"
  selector: {{ .Values.keda_selector }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ print .Values.app_name "-azure-servicebus-auth" }} 
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ print .Values.app_name "-onstarted-scaledobject" }} 
spec:
  scaleTargetRef:
    name: {{ print .Values.app_name "-onstarted" }}
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 15
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: {{ .Values.service_bus_onstarted_topic }} 
      subscriptionName: {{ print .Values.app_name "-onstarted" }}
      namespace: {{ print .Values.app_name "-sb01" }}
      messageCount: "5" 
    authenticationRef:
        name: {{ print .Values.app_name "-azure-servicebus-auth" }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ print .Values.app_name "-onpending-scaledobject" }} 
spec:
  scaleTargetRef:
    name: {{ print .Values.app_name "-onpending" }}
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 15
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: {{ .Values.service_bus_onpending_topic }} 
      subscriptionName: {{ print .Values.app_name "-onpending" }}
      namespace: {{ print .Values.app_name "-sb01" }}
      messageCount: "5" 
    authenticationRef:
        name: {{ print .Values.app_name "-azure-servicebus-auth" }}