apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-submitted
spec:
  topic: ontranscription_submitted
  route: /transcribe
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-onstarted" }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-pending
spec:
  topic: ontranscription_pending
  route: /status
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-onpending" }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-completed
spec:
  topic:  ontranscription_completed
  route: /completed
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-oncompleted" }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-sleep
spec:
  topic:  ontranscription_sleep
  route: /sleep
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-onsleep" }}