apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-submitted
spec:
  topic: ontranscription_submitted
  route: /transcribe
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-onstarted" }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-processing
spec:
  topic: ontranscription_processing
  route: /status
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-onprocessing" }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-completed
spec:
  topic:  ontranscription_completed
  route: /completed
  pubsubname: pubsub
scopes:
- {{ print .Values.app_name "-oncompletion" }}
