---
apiVersion: v1
kind: Namespace
metadata:
  name: kong-gateway
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong-release
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kong-gateway
  chart:
    spec:
      chart: kong
      version: '2.32.0'
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      interval: 1m
  values:
    ingressController:
      installCRDs: false