name: Create Traduire Infrastructure and Deploy Api/UI to Azure 
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'The name of the application to deploy'
        required: true
        default: 'trad8b43xz'
      api_uri:
        description: 'The uri of the api server'
        required: true
        default: 'api.bjd.demo'

jobs:
  create_infrastructure:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        STORAGE_ACCESS_KEY: ${{ secrets.storage_access_key }}
        LOCATION: centralus
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
      
      - name: Create Azure Infrastructure
        shell: pwsh
        run: |
          cd infrastructure
          .\create_infrastructure.ps1 -AppName ${{ github.event.inputs.app_name }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }} -Region ${{ env.LOCATION }} -AdminUser ${{ secrets.ADMIN_USER }} -AdminID ${{ secrets.ADMIN_OBJ_ID}} -StorageAccountKey ${{ secrets.STORAGE_ACCESS_KEY }}

  deploy_api:
    needs: create_infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API
        shell: pwsh
        run: |
          cd deploy
          .\update_firewall.ps1 -AppName ${{ github.event.inputs.app_name }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }}
          .\deploy_application.ps1 -AppName ${{ github.event.inputs.app_name }} -Uri ${{ github.event.inputs.api_uri }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }}

  deploy_ui:
    needs: deploy_api
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

      - name: Deploy UI
        shell: pwsh
        run: |
          cd deploy
          .\deploy_ui.ps1 -AppName ${{ github.event.inputs.app_name }} -ApiUri ${{ github.event.inputs.api_uri }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }}